export const DEFAULT_STITCHING_SERVICES = [
  {
    key: "casual-shirt",
    category: "Shirt",
    name: "Casual Shirt",
    measurementType: "SHIRT",
    measurementGuideImage: "/measurement-guides/shirt.svg",
    measurementFields: [
      { key: "chest", label: "Chest", unit: "in" },
      { key: "waist", label: "Waist", unit: "in" },
      { key: "shoulder", label: "Shoulder", unit: "in" },
      { key: "sleeveLength", label: "Sleeve Length", unit: "in" },
      { key: "garmentLength", label: "Garment Length", unit: "in" },
    ],
    customerPrice: 500,
    tailorRate: 300,
  },
  {
    key: "formal-shirt",
    category: "Shirt",
    name: "Formal Shirt",
    measurementType: "SHIRT",
    measurementGuideImage: "/measurement-guides/shirt.svg",
    measurementFields: [
      { key: "chest", label: "Chest", unit: "in" },
      { key: "waist", label: "Waist", unit: "in" },
      { key: "shoulder", label: "Shoulder", unit: "in" },
      { key: "sleeveLength", label: "Sleeve Length", unit: "in" },
      { key: "garmentLength", label: "Garment Length", unit: "in" },
    ],
    customerPrice: 600,
    tailorRate: 350,
  },
  {
    key: "pants",
    category: "Bottom Wear",
    name: "Pants",
    measurementType: "PANT",
    measurementGuideImage: "/measurement-guides/pant.svg",
    measurementFields: [
      { key: "waist", label: "Waist", unit: "in" },
      { key: "hip", label: "Hip", unit: "in" },
      { key: "thigh", label: "Thigh", unit: "in" },
      { key: "inseam", label: "Inseam", unit: "in" },
      { key: "outseam", label: "Outseam", unit: "in" },
    ],
    customerPrice: 400,
    tailorRate: 240,
  },
  {
    key: "saree-blouse",
    category: "Blouse",
    name: "Saree Blouse",
    measurementType: "BLOUSE",
    measurementGuideImage: "/measurement-guides/blouse.svg",
    measurementFields: [
      { key: "bust", label: "Bust", unit: "in" },
      { key: "waist", label: "Waist", unit: "in" },
      { key: "shoulder", label: "Shoulder", unit: "in" },
      { key: "armhole", label: "Armhole", unit: "in" },
      { key: "blouseLength", label: "Blouse Length", unit: "in" },
    ],
    customerPrice: 450,
    tailorRate: 260,
  },
  {
    key: "kurta",
    category: "Kurta",
    name: "Kurta",
    measurementType: "KURTA",
    measurementGuideImage: "/measurement-guides/kurta.svg",
    measurementFields: [
      { key: "chest", label: "Chest", unit: "in" },
      { key: "waist", label: "Waist", unit: "in" },
      { key: "hip", label: "Hip", unit: "in" },
      { key: "sleeveLength", label: "Sleeve Length", unit: "in" },
      { key: "garmentLength", label: "Kurta Length", unit: "in" },
    ],
    customerPrice: 550,
    tailorRate: 320,
  },
]
